// Dữ liệu sản phẩm — render ra giao diện từ mảng này
// tag: 'moi' | 'hot' | 'khuyen-mai'  (ngẫu nhiên, đổi được)
const PRODUCTS = [
  {
    id: 1,
    name: "Amber Night",
    price: 2450000,
    image: "images/san-pham/Amber-Night.jpg",
    gender: "nam",
    tag: "hot",
    notes: "Hổ phách · Vani · Đàn hương",
  },
  {
    id: 2,
    name: "Black Smoke",
    price: 1980000,
    image: "images/san-pham/Black-Smoke.jpg",
    gender: "nam",
    tag: "moi",
    notes: "Khói · Trầm hương · Da lộn",
  },
  {
    id: 3,
    name: "Blue Horizon",
    price: 1650000,
    image: "images/san-pham/Blue-Horizon.jpg",
    gender: "nam",
    tag: "khuyen-mai",
    notes: "Biển · Bergamot · Xô thơm",
  },
  {
    id: 4,
    name: "Dark Leather",
    price: 3180000,
    image: "images/san-pham/Dark-Leather.jpg",
    gender: "nam",
    tag: "hot",
    notes: "Da lộn · Tiêu đen · Gỗ sồi",
  },
  {
    id: 5,
    name: "Desert Amber",
    price: 2280000,
    image: "images/san-pham/Desert-Amber.jpg",
    gender: "nam",
    tag: "moi",
    notes: "Cát vàng · Hổ phách · Nhang",
  },
  {
    id: 6,
    name: "Forest Wood",
    price: 1750000,
    image: "images/san-pham/Forest-Wood.jpg",
    gender: "nam",
    tag: "khuyen-mai",
    notes: "Gỗ thông · Rêu · Hoắc hương",
  },
  {
    id: 7,
    name: "Golden Oud",
    price: 3850000,
    image: "images/san-pham/Golden-Oud.jpg",
    gender: "nam",
    tag: "hot",
    notes: "Oud · Nhụy hương · Vani",
  },
  {
    id: 8,
    name: "Royal Leather",
    price: 2650000,
    image: "images/san-pham/Royal-Leather.jpg",
    gender: "nam",
    tag: "moi",
    notes: "Da thật · Bergamot · Tiêu",
  },

  {
    id: 9,
    name: "Cherry Kiss",
    price: 2150000,
    image: "images/san-pham/Cherry-Kiss.jpg",
    gender: "nu",
    tag: "moi",
    notes: "Anh đào · Hoa hồng · Vani",
  },
  {
    id: 10,
    name: "Crystal Rose",
    price: 2650000,
    image: "images/san-pham/Crystal-Rose.jpg",
    gender: "nu",
    tag: "hot",
    notes: "Hoa hồng · Lê · Xạ hương",
  },
  {
    id: 11,
    name: "Jasmine Pearl",
    price: 3450000,
    image: "images/san-pham/Jasmine-Pearl.jpg",
    gender: "nu",
    tag: "hot",
    notes: "Hoa nhài · Vani · Đàn hương",
  },
  {
    id: 12,
    name: "Lavender Mist",
    price: 1890000,
    image: "images/san-pham/Lavender-Mist.jpg",
    gender: "nu",
    tag: "khuyen-mai",
    notes: "Oải hương · Cam · Xạ hương",
  },
  {
    id: 13,
    name: "Midnight Rose",
    price: 2980000,
    image: "images/san-pham/Midnight-Rose.jpg",
    gender: "nu",
    tag: "moi",
    notes: "Hoa hồng đêm · Vani · Gỗ",
  },
  {
    id: 14,
    name: "Pink Dream",
    price: 1780000,
    image: "images/san-pham/Pink-Dream.jpg",
    gender: "nu",
    tag: "khuyen-mai",
    notes: "Hoa mẫu đơn · Dâu · Gỗ tuyết",
  },
  {
    id: 15,
    name: "Pure Blossom",
    price: 2350000,
    image: "images/san-pham/Pure-Blossom.jpg",
    gender: "nu",
    tag: "moi",
    notes: "Hoa trắng · Lê · Xạ hương",
  },
  {
    id: 16,
    name: "Velvet Bloom",
    price: 2890000,
    image: "images/san-pham/Velvet-Bloom.jpg",
    gender: "nu",
    tag: "hot",
    notes: "Hoa đậu biếc · Vani · Gỗ",
  },

  {
    id: 17,
    name: "Cool Wave",
    price: 1990000,
    image: "images/san-pham/Cool-Wave.jpg",
    gender: "unisex",
    tag: "hot",
    notes: "Bạc hà · Biển · Xạ hương",
  },
  {
    id: 18,
    name: "Fresh Citrus",
    price: 1540000,
    image: "images/san-pham/Fresh-Citrus.jpg",
    gender: "unisex",
    tag: "khuyen-mai",
    notes: "Cam chanh · Bưởi · Trà xanh",
  },
  {
    id: 19,
    name: "Imperial Musk",
    price: 3250000,
    image: "images/san-pham/Imperial-Musk.jpg",
    gender: "unisex",
    tag: "moi",
    notes: "Xạ hương · Gỗ · Hổ phách",
  },
  {
    id: 20,
    name: "Ocean Breeze",
    price: 1690000,
    image: "images/san-pham/Ocean-Breeze.jpg",
    gender: "unisex",
    tag: "moi",
    notes: "Biển · Bergamot · Hải dương",
  },
  {
    id: 21,
    name: "Silver Rain",
    price: 2190000,
    image: "images/san-pham/Silver-Rain.jpg",
    gender: "unisex",
    tag: "hot",
    notes: "Mưa · Trà đen · Cam",
  },
  {
    id: 22,
    name: "Rose Elan",
    price: 2590000,
    image: "images/san-pham/Rose-Elan.jpg",
    gender: "unisex",
    tag: "khuyen-mai",
    notes: "Hoa hồng · Cam · Gỗ sồi",
  },
  {
    id: 23,
    name: "Royal Musk",
    price: 2890000,
    image: "images/san-pham/Royal-Musk.jpg",
    gender: "unisex",
    tag: "hot",
    notes: "Xạ hương quý · Vani · Gỗ",
  },

  {
    id: 24,
    name: "Sample Gift Set",
    price: 1290000,
    image: "images/qua-tang/Aura Perfume Sample Gift Set.png",
    gender: "qua-tang",
    tag: "moi",
    notes: "Bộ sample 5 chai mini · Hộp giấy",
  },
  {
    id: 25,
    name: "Velvet Pouch",
    price: 1490000,
    image: "images/qua-tang/Aura Perfume Velvet Pouch Elegance.png",
    gender: "qua-tang",
    tag: "khuyen-mai",
    notes: "Túi nhung cao cấp · Dây ruy băng",
  },
  {
    id: 26,
    name: "Gift Wrapping",
    price: 3490000,
    image: "images/qua-tang/AURA Perfume Gift Wrapping Elegance.png",
    gender: "qua-tang",
    tag: "hot",
    notes: "Gói quà sang trọng · Thiệp viết tay",
  },
  {
    id: 27,
    name: "Gift Box Deluxe",
    price: 4900000,
    image: "images/qua-tang/Luxury Aura Perfume Gift Box.png",
    gender: "qua-tang",
    tag: "moi",
    notes: "Hộp quà cao cấp · 2 chai mini",
  },
  {
    id: 28,
    name: "Handwritten Card",
    price: 99000,
    image: "images/qua-tang/Elegant Aura Perfume Handwritten Card Ad.png",
    gender: "qua-tang",
    tag: "khuyen-mai",
    notes: "Thiệp viết tay cao cấp · Bao thư vàng",
  },
];

const TAG_LABEL = { moi: "Mới", hot: "Hot", "khuyen-mai": "Khuyến mãi" };
