// Dữ liệu sản phẩm — render ra giao diện từ mảng này
// tag: 'moi' | 'hot' | 'khuyen-mai'  (ngẫu nhiên, đổi được)
const PRODUCTS = [
  {
    id: 1,
    name: "Amber Night",
    price: 2450000,
    image: "images/san-pham/Amber-Night.jpg",
    gender: "nam",
    tag: "hot",
    notes: "Hổ phách · Vani · Đàn hương",
    desc: "Amber Night — hương thơm tinh tế với tầng hương hổ phách · vani · đàn hương. Thiết kế chai tối giản, sang trọng, phù hợp mọi dịp.",
    stock: 7,
  },
  {
    id: 2,
    name: "Black Smoke",
    price: 1980000,
    image: "images/san-pham/Black-Smoke.jpg",
    gender: "nam",
    tag: "moi",
    notes: "Khói · Trầm hương · Da lộn",
    desc: "Black Smoke — hương thơm tinh tế với tầng hương khói · trầm hương · da lộn. Thiết kế chai tối giản, sang trọng, phù hợp mọi dịp.",
    stock: 14,
  },
  {
    id: 3,
    name: "Blue Horizon",
    price: 1650000,
    image: "images/san-pham/Blue-Horizon.jpg",
    gender: "nam",
    tag: "khuyen-mai",
    notes: "Biển · Bergamot · Xô thơm",
    desc: "Blue Horizon — hương thơm tinh tế với tầng hương biển · bergamot · xô thơm. Thiết kế chai tối giản, sang trọng, phù hợp mọi dịp.",
    stock: 6,
  },
  {
    id: 4,
    name: "Dark Leather",
    price: 3180000,
    image: "images/san-pham/Dark-Leather.jpg",
    gender: "nam",
    tag: "hot",
    notes: "Da lộn · Tiêu đen · Gỗ sồi",
    desc: "Dark Leather — hương thơm tinh tế với tầng hương da lộn · tiêu đen · gỗ sồi. Thiết kế chai tối giản, sang trọng, phù hợp mọi dịp.",
    stock: 13,
  },
  {
    id: 5,
    name: "Desert Amber",
    price: 2280000,
    image: "images/san-pham/Desert-Amber.jpg",
    gender: "nam",
    tag: "moi",
    notes: "Cát vàng · Hổ phách · Nhang",
    desc: "Desert Amber — hương thơm tinh tế với tầng hương cát vàng · hổ phách · nhang. Thiết kế chai tối giản, sang trọng, phù hợp mọi dịp.",
    stock: 5,
  },
  {
    id: 6,
    name: "Forest Wood",
    price: 1750000,
    image: "images/san-pham/Forest-Wood.jpg",
    gender: "nam",
    tag: "khuyen-mai",
    notes: "Gỗ thông · Rêu · Hoắc hương",
    desc: "Forest Wood — hương thơm tinh tế với tầng hương gỗ thông · rêu · hoắc hương. Thiết kế chai tối giản, sang trọng, phù hợp mọi dịp.",
    stock: 12,
  },
  {
    id: 7,
    name: "Golden Oud",
    price: 3850000,
    image: "images/san-pham/Golden-Oud.jpg",
    gender: "nam",
    tag: "hot",
    notes: "Oud · Nhụy hương · Vani",
    desc: "Golden Oud — hương thơm tinh tế với tầng hương oud · nhụy hương · vani. Thiết kế chai tối giản, sang trọng, phù hợp mọi dịp.",
    stock: 4,
  },
  {
    id: 8,
    name: "Royal Leather",
    price: 2650000,
    image: "images/san-pham/Royal-Leather.jpg",
    gender: "nam",
    tag: "moi",
    notes: "Da thật · Bergamot · Tiêu",
    desc: "Royal Leather — hương thơm tinh tế với tầng hương da thật · bergamot · tiêu. Thiết kế chai tối giản, sang trọng, phù hợp mọi dịp.",
    stock: 11,
  },

  {
    id: 9,
    name: "Cherry Kiss",
    price: 2150000,
    image: "images/san-pham/Cherry-Kiss.jpg",
    gender: "nu",
    tag: "moi",
    notes: "Anh đào · Hoa hồng · Vani",
    desc: "Cherry Kiss — hương thơm tinh tế với tầng hương anh đào · hoa hồng · vani. Thiết kế chai tối giản, sang trọng, phù hợp mọi dịp.",
    stock: 3,
  },
  {
    id: 10,
    name: "Crystal Rose",
    price: 2650000,
    image: "images/san-pham/Crystal-Rose.jpg",
    gender: "nu",
    tag: "hot",
    notes: "Hoa hồng · Lê · Xạ hương",
    desc: "Crystal Rose — hương thơm tinh tế với tầng hương hoa hồng · lê · xạ hương. Thiết kế chai tối giản, sang trọng, phù hợp mọi dịp.",
    stock: 10,
  },
  {
    id: 11,
    name: "Jasmine Pearl",
    price: 3450000,
    image: "images/san-pham/Jasmine-Pearl.jpg",
    gender: "nu",
    tag: "hot",
    notes: "Hoa nhài · Vani · Đàn hương",
    desc: "Jasmine Pearl — hương thơm tinh tế với tầng hương hoa nhài · vani · đàn hương. Thiết kế chai tối giản, sang trọng, phù hợp mọi dịp.",
    stock: 2,
  },
  {
    id: 12,
    name: "Lavender Mist",
    price: 1890000,
    image: "images/san-pham/Lavender-Mist.jpg",
    gender: "nu",
    tag: "khuyen-mai",
    notes: "Oải hương · Cam · Xạ hương",
    desc: "Lavender Mist — hương thơm tinh tế với tầng hương oải hương · cam · xạ hương. Thiết kế chai tối giản, sang trọng, phù hợp mọi dịp.",
    stock: 9,
  },
  {
    id: 13,
    name: "Midnight Rose",
    price: 2980000,
    image: "images/san-pham/Midnight-Rose.jpg",
    gender: "nu",
    tag: "moi",
    notes: "Hoa hồng đêm · Vani · Gỗ",
    desc: "Midnight Rose — hương thơm tinh tế với tầng hương hoa hồng đêm · vani · gỗ. Thiết kế chai tối giản, sang trọng, phù hợp mọi dịp.",
    stock: 1,
  },
  {
    id: 14,
    name: "Pink Dream",
    price: 1780000,
    image: "images/san-pham/Pink-Dream.jpg",
    gender: "nu",
    tag: "khuyen-mai",
    notes: "Hoa mẫu đơn · Dâu · Gỗ tuyết",
    desc: "Pink Dream — hương thơm tinh tế với tầng hương hoa mẫu đơn · dâu · gỗ tuyết. Thiết kế chai tối giản, sang trọng, phù hợp mọi dịp.",
    stock: 8,
  },
  {
    id: 15,
    name: "Pure Blossom",
    price: 2350000,
    image: "images/san-pham/Pure-Blossom.jpg",
    gender: "nu",
    tag: "moi",
    notes: "Hoa trắng · Lê · Xạ hương",
    desc: "Pure Blossom — hương thơm tinh tế với tầng hương hoa trắng · lê · xạ hương. Thiết kế chai tối giản, sang trọng, phù hợp mọi dịp.",
    stock: 0,
  },
  {
    id: 16,
    name: "Velvet Bloom",
    price: 2890000,
    image: "images/san-pham/Velvet-Bloom.jpg",
    gender: "nu",
    tag: "hot",
    notes: "Hoa đậu biếc · Vani · Gỗ",
    desc: "Velvet Bloom — hương thơm tinh tế với tầng hương hoa đậu biếc · vani · gỗ. Thiết kế chai tối giản, sang trọng, phù hợp mọi dịp.",
    stock: 7,
  },

  {
    id: 17,
    name: "Cool Wave",
    price: 1990000,
    image: "images/san-pham/Cool-Wave.jpg",
    gender: "unisex",
    tag: "hot",
    notes: "Bạc hà · Biển · Xạ hương",
    desc: "Cool Wave — hương thơm tinh tế với tầng hương bạc hà · biển · xạ hương. Thiết kế chai tối giản, sang trọng, phù hợp mọi dịp.",
    stock: 14,
  },
  {
    id: 18,
    name: "Fresh Citrus",
    price: 1540000,
    image: "images/san-pham/Fresh-Citrus.jpg",
    gender: "unisex",
    tag: "khuyen-mai",
    notes: "Cam chanh · Bưởi · Trà xanh",
    desc: "Fresh Citrus — hương thơm tinh tế với tầng hương cam chanh · bưởi · trà xanh. Thiết kế chai tối giản, sang trọng, phù hợp mọi dịp.",
    stock: 6,
  },
  {
    id: 19,
    name: "Imperial Musk",
    price: 3250000,
    image: "images/san-pham/Imperial-Musk.jpg",
    gender: "unisex",
    tag: "moi",
    notes: "Xạ hương · Gỗ · Hổ phách",
    desc: "Imperial Musk — hương thơm tinh tế với tầng hương xạ hương · gỗ · hổ phách. Thiết kế chai tối giản, sang trọng, phù hợp mọi dịp.",
    stock: 13,
  },
  {
    id: 20,
    name: "Ocean Breeze",
    price: 1690000,
    image: "images/san-pham/Ocean-Breeze.jpg",
    gender: "unisex",
    tag: "moi",
    notes: "Biển · Bergamot · Hải dương",
    desc: "Ocean Breeze — hương thơm tinh tế với tầng hương biển · bergamot · hải dương. Thiết kế chai tối giản, sang trọng, phù hợp mọi dịp.",
    stock: 5,
  },
  {
    id: 21,
    name: "Silver Rain",
    price: 2190000,
    image: "images/san-pham/Silver-Rain.jpg",
    gender: "unisex",
    tag: "hot",
    notes: "Mưa · Trà đen · Cam",
    desc: "Silver Rain — hương thơm tinh tế với tầng hương mưa · trà đen · cam. Thiết kế chai tối giản, sang trọng, phù hợp mọi dịp.",
    stock: 12,
  },
  {
    id: 22,
    name: "Rose Elan",
    price: 2590000,
    image: "images/san-pham/Rose-Elan.jpg",
    gender: "unisex",
    tag: "khuyen-mai",
    notes: "Hoa hồng · Cam · Gỗ sồi",
    desc: "Rose Elan — hương thơm tinh tế với tầng hương hoa hồng · cam · gỗ sồi. Thiết kế chai tối giản, sang trọng, phù hợp mọi dịp.",
    stock: 4,
  },
  {
    id: 23,
    name: "Royal Musk",
    price: 2890000,
    image: "images/san-pham/Royal-Musk.jpg",
    gender: "unisex",
    tag: "hot",
    notes: "Xạ hương quý · Vani · Gỗ",
    desc: "Royal Musk — hương thơm tinh tế với tầng hương xạ hương quý · vani · gỗ. Thiết kế chai tối giản, sang trọng, phù hợp mọi dịp.",
    stock: 11,
  },

  {
    id: 24,
    name: "Sample Gift Set",
    price: 1290000,
    image: "images/qua-tang/Aura Perfume Sample Gift Set.png",
    gender: "qua-tang",
    tag: "moi",
    notes: "Bộ sample 5 chai mini · Hộp giấy",
    desc: "Sample Gift Set — hương thơm tinh tế với tầng hương bộ sample 5 chai mini · hộp giấy. Thiết kế chai tối giản, sang trọng, phù hợp mọi dịp.",
    stock: 3,
  },
  {
    id: 25,
    name: "Velvet Pouch",
    price: 1490000,
    image: "images/qua-tang/Aura Perfume Velvet Pouch Elegance.png",
    gender: "qua-tang",
    tag: "khuyen-mai",
    notes: "Túi nhung cao cấp · Dây ruy băng",
    desc: "Velvet Pouch — hương thơm tinh tế với tầng hương túi nhung cao cấp · dây ruy băng. Thiết kế chai tối giản, sang trọng, phù hợp mọi dịp.",
    stock: 10,
  },
  {
    id: 26,
    name: "Gift Wrapping",
    price: 3490000,
    image: "images/qua-tang/AURA Perfume Gift Wrapping Elegance.png",
    gender: "qua-tang",
    tag: "hot",
    notes: "Gói quà sang trọng · Thiệp viết tay",
    desc: "Gift Wrapping — hương thơm tinh tế với tầng hương gói quà sang trọng · thiệp viết tay. Thiết kế chai tối giản, sang trọng, phù hợp mọi dịp.",
    stock: 2,
  },
  {
    id: 27,
    name: "Gift Box Deluxe",
    price: 4900000,
    image: "images/qua-tang/Luxury Aura Perfume Gift Box.png",
    gender: "qua-tang",
    tag: "moi",
    notes: "Hộp quà cao cấp · 2 chai mini",
    desc: "Gift Box Deluxe — hương thơm tinh tế với tầng hương hộp quà cao cấp · 2 chai mini. Thiết kế chai tối giản, sang trọng, phù hợp mọi dịp.",
    stock: 9,
  },
  {
    id: 28,
    name: "Handwritten Card",
    price: 99000,
    image: "images/qua-tang/Elegant Aura Perfume Handwritten Card Ad.png",
    gender: "qua-tang",
    tag: "khuyen-mai",
    notes: "Thiệp viết tay cao cấp · Bao thư vàng",
    desc: "Handwritten Card — hương thơm tinh tế với tầng hương thiệp viết tay cao cấp · bao thư vàng. Thiết kế chai tối giản, sang trọng, phù hợp mọi dịp.",
    stock: 5,
  },
];

const TAG_LABEL = { moi: "Mới", hot: "Hot", "khuyen-mai": "Khuyến mãi" };
